* 第39课

** 三、练习与运用

*** 2. 句子练习

**** A

***** 总（是）
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: c7ad2028-911b-4a2a-888a-e831ead2bfd5
:END:

******* 句子填空

他对工作很不认真，你每次找他帮助解决问题，他🟦。

******* 词语

说要研究研究

******* 答案

总是说要研究研究

****** 2
:PROPERTIES:
:ID: 14b8aa6a-ef2f-439a-8c98-b18558c9961f
:END:

******* 句子填空

他学习很努力，也很认真，他的成绩🟦。

******* 词语

全班第一

******* 答案

总是全班第一

****** 3
:PROPERTIES:
:ID: fd33e2d8-934d-4bea-abe8-ec80dd3afd14
:END:

******* 句子填空

北京王府井大街🟦。

******* 词语

那么热闹

******* 答案

总是那么热闹

****** 4
:PROPERTIES:
:ID: eea493f1-f6ae-4e8d-a670-48a46cef9325
:END:

******* 句子填空

他们俩在食堂🟦，别人听了觉重很别扭。

******* 词语

大声地说笑

******* 答案

总是大声地说笑

****** 5
:PROPERTIES:
:ID: 9e0cc156-23c4-4bdc-a045-ba043b71b9e1
:END:

******* 句子填空

他去了好几次北京，🟦。

******* 词语

没时间登长城

******* 答案

总也没时间登长城

***** 终于
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: 14d2bac4-72dd-4785-bfe7-b75b4e78938c
:END:

******* 句子填空

这么多的作业，他🟦。

******* 词语

做完

******* 答案

终于做完

****** 2
:PROPERTIES:
:ID: 92d8657b-a8cc-4a5c-a51b-dc685ea97bbd
:END:

******* 句子填空

他很早就想买这本书，今天他🟦。

******* 词语

买到

******* 答案

终于买到

****** 3
:PROPERTIES:
:ID: e44427c2-4179-4f83-9a0f-4edd01aafb9d
:END:

******* 句子填空

这个问题已经研究好几次了，这次🟦

******* 词语

把它解决

******* 答案

终于把它解决

****** 4
:PROPERTIES:
:ID: c6e1275a-b612-4c1a-b4f9-90137285de22
:END:

******* 句子填空

他很早就想参翙兵马俑，今天来西安旅游，他🟦。

******* 词语

看到

******* 答案

终于看到了

****** 5
:PROPERTIES:
:ID: 5cf8cd9f-53b2-4e68-99c5-42234a433365
:END:

******* 句子填空

他打扫了一个上午，房间🟦。

******* 词语

干净

******* 答案

终于干净了

***** 必须（不必）
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: c18d20bf-f394-4106-868d-ccc6e63c75bf
:END:

******* 句子填空

我们🟦以前到火车站，才能坐上今天八点一刻去广州的火车。

******* 词语

no value

******* 答案



****** 2
:PROPERTIES:
:ID: ec926a8a-1142-44f7-81f6-90cfb3fb1a47
:END:

******* 句子填空

你🟦，才能学好外语。

******* 词语

no value

******* 答案



****** 3
:PROPERTIES:
:ID: d1a040c1-96ff-4c7f-901d-aae03925d8a8
:END:

******* 句子填空

小燕子说🟦，才能当大饭店里的厨师。

******* 词语

no value

******* 答案



****** 4
:PROPERTIES:
:ID: 608e1628-3e64-4299-ae1c-0ff5a9284152
:END:

******* 句子填空

车开不上去了，🟦。

******* 词语

no value

******* 答案



****** 5
:PROPERTIES:
:ID: 88fedf8e-b9fb-4b72-95cf-cc7b0364b9a5
:END:

******* 句子填空

您🟦那么着急，他们一定会帮助您解决问题的。

******* 词语

no value

******* 答案



***** 究竟
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: 384db21d-a177-45bf-bfe0-440b70c7dd7d
:END:

******* 句子填空

他们提的意见🟦？

******* 词语

对

******* 答案



****** 2
:PROPERTIES:
:ID: 0170bd5a-1b26-47c3-b065-f66f14f8acfa
:END:

******* 句子填空

小燕子做的菜🟦？

******* 词语

好吃

******* 答案



****** 3
:PROPERTIES:
:ID: e7d3ef02-ad39-4613-8f4f-016e82f5b1b6
:END:

******* 句子填空

我们班🟦？

******* 词语

考口语

******* 答案



****** 4
:PROPERTIES:
:ID: 17d08637-7741-43fc-84ee-5c701523b5d7
:END:

******* 句子填空

他🟦？

******* 词语

参加比赛

******* 答案



****** 5
:PROPERTIES:
:ID: ed4b8ae9-6cd5-43ad-a6b5-97c09f7a6827
:END:

******* 句子填空

张经理🟦？

******* 词语

回公司

******* 答案

* 第40课

** 一、课文

*** 一

**** 内容
:PROPERTIES:
:NOTETYPE: aabca9f4-d7dc-4ae0-a92d-5187b3b41b52
:END:

陆雨平：有人提出妇女结婚以后，[[file:306cbb4a-ca58-441d-bdec-7c303557483b.flac][(audio)]]特别是有了孩子以后，[[file:f494eba3-293c-4845-a4c1-c41169ff9fd7.flac][(audio)]]应该回到家里做“全职太太”，[[file:f16dcf60-3ddb-47b5-8450-a8903e0b4b37.flac][(audio)]]因为她们要照顾孩子，[[file:05cc2c96-a89a-4ee4-99d8-572ad85a0810.flac][(audio)]]要做家务。[[file:4e904cf4-7ec8-4586-9285-a0d30ee74c7a.flac][(audio)]]对这个问题，[[file:48946a2b-b554-40da-b50b-429544523b0c.flac][(audio)]]你们有什么看法？[[file:7f509a91-92df-4581-bc51-7a480f1c22e6.flac][(audio)]]

陈老师：这个主意很可能是男人想出来的吧？[[file:ee046613-e51e-4131-a17a-27a50cf00761.flac][(audio)]]妇女经过了多少个世纪的努力，[[file:2c887647-fcf8-47f7-a304-d3120e9111a8.flac][(audio)]]终于从家里走出来，[[file:4b00b6b0-3dcd-4cbe-aaaa-d0b3dac4ebea.flac][(audio)]]得到工作的权利，[[file:f5b8b959-cd5d-421c-a257-553afa3f6293.flac][(audio)]]而且能发挥“半边天”的作用。[[file:23f6bc68-ac31-4ec9-afe0-a2e24cd4c248.flac][(audio)]]这是社会的进步。[[file:d6064e1e-bbc6-417b-9fe0-448ddadfa6d3.flac][(audio)]]现在怎么又要让妇女回到厨房去呢？[[file:3a59f2b6-66e9-4228-a33c-6b1701698599.flac][(audio)]]

陆雨平：这不只是一些男人的看法，[[file:bd3c8b1a-0037-435e-a18a-a7d2c653b559.flac][(audio)]]有些妇女也有这样的看法。[[file:4007597d-06a8-422b-8a35-e7264421b8b7.flac][(audio)]]大家都知道，[[file:de577a22-8b3d-453a-9d15-177a5ae0016a.flac][(audio)]]城市里几乎都是双职工的家庭，[[file:114550a1-c859-4e90-916e-44298ae88a45.flac][(audio)]]丈夫和妻子每天都要在外边工作，[[file:17bbe1c0-cc1a-4f41-950a-85bd1b86b094.flac][(audio)]]他们没时间照顾孩子。[[file:04be9a92-2363-4177-a36e-e7e26bec5770.flac][(audio)]]没有一个母亲不关心自己的孩子，[[file:6b30601c-247b-4381-87d4-ff770cd896ab.flac][(audio)]]要是妇女回家，[[file:d6e7dbb6-091c-4bcc-aa52-aa674af61907.flac][(audio)]]孩子的教育问题就可以解决得更好。[[file:3672997a-9c8d-474c-8d4d-49475e74e90d.flac][(audio)]]这不是看不起妇女，[[file:2c7ddef3-1b06-47a9-bba2-358000220543.flac][(audio)]]而是为了更好得发挥妇女的作用。[[file:e43b5d8e-be9e-4d86-b669-444d2483723f.flac][(audio)]]

王小云：我认为，照顾孩子和做家务[[file:eabbffed-ff1a-4b32-9d9f-ae9c59632f25.flac][(audio)]]不只是妇女的事儿，[[file:d0d3d664-1d74-4ef7-9888-55e68d901c30.flac][(audio)]]也是男人的事儿。应该 男女都一样：[[file:f737aad9-2407-4fab-b711-164e134f132b.flac][(audio)]]要是愿意回家照顾孩子，就回家照顾孩子；[[file:4ac05c5b-7c8f-40fa-9842-f0850050aa64.flac][(audio)]]要是愿意出来工作，就出来工作。[[file:7fae16e3-6745-480e-99eb-50465027760f.flac][(audio)]]

陆雨平：如果大家都愿意回家照顾孩子，[[file:836a5c32-173c-4548-bad7-c0794a545e78.flac][(audio)]]不愿意出来工作，怎么办？[[file:10565814-9524-4ccf-ac36-8fdf30bc9c72.flac][(audio)]]

王小云：这不可能。不会没有人愿意出来工作。[[file:486a9ae1-928b-48ff-b34b-201c4773a0a9.flac][(audio)]]

陆雨平：有人还认为，中国人口太多，[[file:ac516d51-e2c0-466e-99a3-49b74c69f932.flac][(audio)]]就业的问题很大；要是妇女回家，[[file:2e73f7e1-b3cb-4aca-8f41-057e2e60d2fe.flac][(audio)]]这个问题就比较容易解决了。[[file:e19a1547-f5ee-4c20-b7a9-961eb1376037.flac][(audio)]]

陈老师：为了解决就业问题，[[file:693a60dd-b658-4d3c-8fa7-02088de8753a.flac][(audio)]]就必须让妇女回家吗？[[file:b05ff0a4-e6c3-45c0-b126-3cdd5f1d1168.flac][(audio)]]这不公平。[[file:63bf636e-fde1-4186-a09f-ce39a176e29c.flac][(audio)]]我觉得，[[file:fc9d5e27-55e7-4bf8-ac84-3a412f861123.flac][(audio)]]现在首先要解决[[file:31dfbe95-f22a-4588-9ac6-840bfedab018.flac][(audio)]]就业中的男女平等问题。[[file:62b35270-d2ae-4c11-8dc8-3cd7e3cfe373.flac][(audio)]]比如说，有的工作男女都可以干，[[file:db2270ad-3e9a-46f7-80cc-3147c182f010.flac][(audio)]]可是一些单位只要男的，不要女的。[[file:c7c2e4c3-6ca6-432d-a02d-cfe0ad060a7f.flac][(audio)]]我认为这是很不对的。[[file:42e031c2-8e61-4f0e-949b-4af582d5b801.flac][(audio)]]

陆雨平：你不认为有的工作男人来做更合适吗？[[file:89627733-aff8-40a6-9099-35de0514f60c.flac][(audio)]]

王小云：当然有，[[file:fd57730a-3016-4cd8-afb6-209cc5733569.flac][(audio)]]但是也有的工作妇女比男人做得更好。[[file:04d9b5e7-bda2-4800-a4a1-6a764e7b9a46.flac][(audio)]]重要的是，[[file:9e48693f-7b45-44c6-ab57-e523e869e082.flac][(audio)]]男女都应该有公平竞争的机会。[[file:7a439768-9039-4d31-8075-690b10a5a1aa.flac][(audio)]]

陆雨平：最后，我们不能不谈到这个问题：陈老师，[[file:2b816d62-5ed8-4f8e-bf2a-8ea7ae2d8e38.flac][(audio)]]你认为究竟应该怎样[[file:54a63791-469c-4506-a21c-847944e1ac2d.flac][(audio)]]才能实现男女平等呢？[[file:f1048134-9bcd-4e53-84d3-3b11ef9b2891.flac][(audio)]]

陈老师：只有在各个方面[[file:c1ea3be3-7007-4287-8502-909d5c5d09f4.flac][(audio)]]只有在各个方面[[file:bc84496b-c156-462f-bb53-f140efdeb79e.flac][(audio)]]男女才能平等。[[file:3d08c16d-7068-456c-9ef8-82b7375b7aee.flac][(audio)]]

陆雨平：谢谢你们接受我的访问。[[file:fb2b36c6-69e2-447c-9c5e-04de278ab408.flac][(audio)]]

**** 生词
:PROPERTIES:
:NOTETYPE: 2428d9df-45bc-4c06-806a-8e4536124689
:END:

***** 1
:PROPERTIES:
:ID: 7c0d572c-6902-4760-b90a-230241855900
:END:

****** 简体字

半边天

****** 词性

N

****** 拼音

bànbiāntiān

****** 西语翻译

medio cielo

****** 音频

7d621915-1015-42ef-9b0f-d443b4fd58f6.mp3

***** 2
:PROPERTIES:
:ID: 51433c83-b55c-47d2-b043-f16977587fc2
:END:

****** 简体字

全职

****** 词性

A

****** 拼音

quánzhí

****** 西语翻译

trabajo a tiempo completo

****** 音频

51f48554-fe87-4306-973d-5264933a4e33.mp3

***** 3
:PROPERTIES:
:ID: ddf5749f-293f-4728-a489-cfee6f453fce
:END:

****** 简体字

妇女

****** 词性

N

****** 拼音

fùnǚ

****** 西语翻译

mujer

****** 音频

659568e2-f870-457c-9681-f172895f6944.mp3

***** 4
:PROPERTIES:
:ID: a2c25102-a290-4c28-a1a4-a47b38f2f533
:END:

****** 简体字

照顾

****** 词性

V

****** 拼音

zhàogù

****** 西语翻译

cuidar (de)

****** 音频

9ce1b72a-f0c7-4af4-ac9d-46e9480f536c.mp3

***** 5
:PROPERTIES:
:ID: bec91d76-2c03-45c5-b404-9d1963670a83
:END:

****** 简体字

家务

****** 词性

N

****** 拼音

jiāwù

****** 西语翻译

tarea de casa

****** 音频

ac37aa7f-33d5-45c8-9141-59fee8794650.mp3

***** 6
:PROPERTIES:
:ID: 00118224-8621-43c3-a9fa-694a951aed84
:END:

****** 简体字

男人

****** 词性

N

****** 拼音

nánrén

****** 西语翻译

hombre

****** 音频

12da54a5-2275-4311-9cf6-144ae233cfd9.mp3

***** 7
:PROPERTIES:
:ID: b20e307a-dadc-4805-ade6-ddf9b5940c77
:END:

****** 简体字

权利

****** 词性

N

****** 拼音

quánlì

****** 西语翻译

derecho

****** 音频

ac1d77c5-f103-487c-9bd4-3259910c9a9e.mp3

***** 8
:PROPERTIES:
:ID: 8289f2aa-d52d-4431-bd76-794dee4250aa
:END:

****** 简体字

发挥

****** 词性

V

****** 拼音

fāhuī

****** 西语翻译

desempecho, dessarollar

****** 音频

b1c560cd-c4d9-46a2-b318-eb32ce3775f9.mp3

***** 9
:PROPERTIES:
:ID: 8a3a8cb7-6c7e-472f-90ba-0d27eeaae36a
:END:

****** 简体字

作用

****** 词性

N

****** 拼音

zuòyòng

****** 西语翻译

papel, función

****** 音频

13f83647-51dd-4806-93c2-d34c8904a5a2.mp3

***** 10
:PROPERTIES:
:ID: f4e00be9-9c5b-4076-8f6b-998eebb98b1f
:END:

****** 简体字

社会

****** 词性

N

****** 拼音

shèhuì

****** 西语翻译

sociedad

****** 音频

662450f2-6809-4e35-8c1c-0607c5b03195.mp3

***** 11
:PROPERTIES:
:ID: afcae446-9bb2-4f9a-bf5e-6826c05d4b29
:END:

****** 简体字

不只

****** 词性

Conj.

****** 拼音

bùzhǐ

****** 西语翻译

no solo, no solamente

****** 音频

89df629e-f706-4b19-af82-0242140e20af.mp3

***** 12
:PROPERTIES:
:ID: 29836127-fa92-4a87-82f7-cadc7ebfc129
:END:

****** 简体字

几乎

****** 词性

Adv.

****** 拼音

jīhū

****** 西语翻译

casi

****** 音频

0008e194-d808-46c5-a5bc-1b428f530fb2.mp3

***** 13
:PROPERTIES:
:ID: f3822314-5e49-4390-baee-e43193f463c5
:END:

****** 简体字

双职工

****** 词性

N

****** 拼音

shuāngzhígōng

****** 西语翻译

matrimonio que trabaja

****** 音频

4627728e-b5f7-4645-b2bd-e014760ccade.mp3

***** 14
:PROPERTIES:
:ID: 3fd5f3d7-4a9a-4462-ac75-013c098d37a5
:END:

****** 简体字

家庭

****** 词性

N

****** 拼音

jiātíng

****** 西语翻译

familia

****** 音频

b0990e41-5bad-4be9-98e1-66cd551b67e9.mp3

***** 15
:PROPERTIES:
:ID: b79b5c7b-0bad-4cde-804c-694dda70cdcd
:END:

****** 简体字

要是

****** 词性

Conj.

****** 拼音

yàoshi

****** 西语翻译

si, en caso de (qye)

****** 音频

c0229780-0349-446b-8e03-67c0f004aa19.mp3

***** 16
:PROPERTIES:
:ID: 875fb9a0-9e25-4eb8-a177-2119f6c53f81
:END:

****** 简体字

看不起

****** 词性

V

****** 拼音

kànbuqǐ

****** 西语翻译

despreciar

****** 音频

aa2de6d6-32d4-40b8-827b-ec669f3d3e34.mp3

***** 17
:PROPERTIES:
:ID: c5c0dee6-19d1-4956-9d66-4947ae55b16d
:END:

****** 简体字

为了

****** 词性

Prep.

****** 拼音

wèile

****** 西语翻译

para, por

****** 音频

6d741333-4c52-479c-bd88-ccdab5df56dd.mp3

***** 18
:PROPERTIES:
:ID: 6f2c0f41-5b42-4b13-917c-5a9d0bce5ecd
:END:

****** 简体字

男女

****** 词性

N

****** 拼音

nánnǚ

****** 西语翻译

hombres y mujeres

****** 音频

354e1fec-f2b4-48fd-b39f-c980e702766a.mp3

***** 19
:PROPERTIES:
:ID: e3a331e5-2c98-47a0-9099-709d1ea4fea8
:END:

****** 简体字

就业

****** 词性

VO

****** 拼音

jiùyè

****** 西语翻译

conseguir trabajo, incorporarse al mercado laboral

****** 音频

365f7370-3326-4055-9d0f-7c3196b5d1b3.mp3

***** 20
:PROPERTIES:
:ID: 11167515-9014-401e-a44d-9dab59daf225
:END:

****** 简体字

公平

****** 词性

A

****** 拼音

gōngpíng

****** 西语翻译

justo

****** 音频

ffbf20f5-0fd7-40ac-aa4a-561bd5556fa3.mp3

***** 21
:PROPERTIES:
:ID: 60c8306b-c675-436a-bb8d-e365e268a2e6
:END:

****** 简体字

平等

****** 词性

A

****** 拼音

píngděng

****** 西语翻译

igual

****** 音频

b2e46021-73cc-49a8-a0d1-471ec0ba1baf.mp3

***** 22
:PROPERTIES:
:ID: 7ac8fecd-4e29-41f3-83b4-89c3f82b79bf
:END:

****** 简体字

单位

****** 词性

N

****** 拼音

dānwèi

****** 西语翻译

unidad, entidad (sitio de trabajo, organización, etc.)

****** 音频

93677e8e-3305-4627-8d00-8d3975f6fcc7.mp3

***** 23
:PROPERTIES:
:ID: 6bcd41f6-25b3-4007-9ff1-67f1510be9b6
:END:

****** 简体字

竞争

****** 词性

V

****** 拼音

jìngzhēng

****** 西语翻译

competir

****** 音频

5ea94d19-4ba6-42ed-9d01-ea4caf3cb898.mp3

***** 24
:PROPERTIES:
:ID: 000faea7-fdc0-4f6b-ad37-2281c4f0f5b3
:END:

****** 简体字

机会

****** 词性

N

****** 拼音

jīhuì

****** 西语翻译

oportunidad, ocasión

****** 音频

f6bf86d1-1332-4ed4-b0c1-64f94bd9c42a.mp3

***** 25
:PROPERTIES:
:ID: 5fdc9daa-97c4-406e-b92b-71b2fb2adcc0
:END:

****** 简体字

只有

****** 词性

Conj.

****** 拼音

zhǐyǒu

****** 西语翻译

solo, solamente

****** 音频

b9231e90-e2ee-47a4-a519-3bc153f5af03.mp3

***** 26
:PROPERTIES:
:ID: 9713e077-e377-4acb-bc76-5bcfc839fa27
:END:

****** 简体字

方面

****** 词性

N

****** 拼音

fāngmiàn

****** 西语翻译

aspecto, lado

****** 音频

df1f94cc-c5dc-4324-8dfa-9c02afa3a8ae.mp3

***** 27
:PROPERTIES:
:ID: dd1645a5-4bfa-4050-91c1-7d57b0d1dd51
:END:

****** 简体字

同样

****** 词性

A

****** 拼音

tóngyàng

****** 西语翻译

mismo, igual, similar

****** 音频

cdb4d488-4cdb-4d39-80b6-4996c4f5b014.mp3

*** 二

**** 内容
:PROPERTIES:
:NOTETYPE: aabca9f4-d7dc-4ae0-a92d-5187b3b41b52
:END:

各位老师，各位同学：[[file:d510c1a0-fa97-4976-8ea5-a7fb71a04660.flac][(audio)]]

我很高兴有机会跟大家谈谈[[file:4249f563-8aca-4eab-8246-0e9012f6bdfb.flac][(audio)]]中国妇女的地位问题。[[file:55ae4fd7-d222-476b-b250-d82ee031d1d5.flac][(audio)]]这是一个很大的问题，[[file:76972252-533c-41c0-b6c9-d6f55723e528.flac][(audio)]]我想从四个方面简单地谈一谈。[[file:0e37c3c7-e140-4f23-a9c2-c1c42530c1e0.flac][(audio)]]

首先，[[file:df68bce0-665d-437b-8b9e-63da0a1fb675.flac][(audio)]]我要谈一下中国妇女的社会地位。[[file:dcbe4ec0-0a93-4d22-9b82-ec2bf92ec740.flac][(audio)]]

中国人常说妇女是“半边天”。[[file:231a6cc7-102e-4071-8111-d7b2a0f36f91.flac][(audio)]]“半边天”是什么意思呢？[[file:563ea2df-c0e7-4739-9e58-44a1cba6caa2.flac][(audio)]]就是妇女几乎担负着一半的社会工作。[[file:7921b3c1-cec1-47e0-a443-a027d1d77632.flac][(audio)]]她们跟男人一样，[[file:12a9d719-fb26-42cf-a148-ef7361dd8624.flac][(audio)]]对社会进步和国家的发展发挥着重要的作用。[[file:478834b9-2670-4c27-ac0d-b4e8391c2232.flac][(audio)]]在全中国的职工中，[[file:e94cb207-706f-46c2-8fc0-e689f8c2a9ba.flac][(audio)]]女职工占百分之四十。[[file:b424a787-dc26-4e08-9e30-0a048b3478ec.flac][(audio)]]现在中国既有女部长、女外交官、女经理，[[file:8a3ff53c-955b-4d84-84b7-54ea6da7df5e.flac][(audio)]]又有女科学家、女教授、女画家、女诗人……[[file:5276da84-3778-4047-b058-24078110b149.flac][(audio)]]一般地说，[[file:e33c004b-7712-4bbe-87bc-b32eff359b1f.flac][(audio)]]男人能做的工作没有妇女不能做的。[[file:c355bf30-5eed-4064-bc76-a0186bdeea05.flac][(audio)]]有的工作，比如[[file:7b3fef7d-8ca9-4a0e-b74d-7a5d434e9241.flac][(audio)]]纺织工人、护士，几乎都是妇女；[[file:4a4c282d-39fb-4dd3-b368-4cd8b2273da6.flac][(audio)]]中小学教师，大学里的外语老师，[[file:e8fd5a32-5134-416f-b72e-c76d0d090bb2.flac][(audio)]]也是女的比男的多。[[file:e8655416-0f50-49fc-b075-c863569cfc85.flac][(audio)]]大家都知道，[[file:a85630d6-00d6-457e-a288-98201a6e6d2c.flac][(audio)]]在中国两千多年的封建社会中，[[file:48135599-a779-497d-8998-a952e2f32cb3.flac][(audio)]]妇女没有社会地位。[[file:1f684e11-8cd9-4308-9d3c-529533cdbf21.flac][(audio)]]她们一辈子要服从自己的父母、丈夫和儿子。[[file:af9f338e-5d48-4356-8c06-aece98831bc0.flac][(audio)]]她们没有受教育的权利，[[file:6ad19347-fc22-418d-a4ab-802bf7e17256.flac][(audio)]]也不能走出家门到外边去工作，[[file:29faf3d7-6c64-40d0-ac61-c9b426ec2c48.flac][(audio)]]只能在家里做家务，照顾丈夫和孩子。[[file:68abea5d-0867-4415-8efa-a85763a76367.flac][(audio)]]现在情况不同了，[[file:bf1cc510-448b-4ea9-998e-8137abc8923e.flac][(audio)]]妇女能发挥“半边天”的作用，[[file:68e287b4-aa68-4bca-8b68-486b2b09377f.flac][(audio)]]在社会上有了跟男子平等的地位。[[file:648c2623-88a7-4c3c-990f-c3c6f2229ccd.flac][(audio)]]这是中国社会的进步。[[file:ed535155-daf9-4ed2-8b32-31eda707ed77.flac][(audio)]]

第二，中国妇女在家庭里的地位。[[file:8a488bc4-2182-4b7c-a1b2-e45286c271a4.flac][(audio)]]

一般地说，妇女只有社会地位提高了，[[file:42a5480e-8023-42a7-b879-5431e811da19.flac][(audio)]]在家庭里的地位才能提高。[[file:8a816fd4-05b3-4781-b31d-aefe463f2d78.flac][(audio)]]她们在外边有自己的工作和经济收入，[[file:362bd486-8eae-4f0a-b983-86a2a9626974.flac][(audio)]]在家里就有了平等的地位。[[file:ddc7ae55-1612-4f3c-ba46-3829de7d994a.flac][(audio)]]过去，家里的大事常常由丈夫决定，[[file:a882a809-8561-41fa-a1bf-bee5f90b95aa.flac][(audio)]]现在丈夫要跟妻子商量。[[file:bed9c872-cc9f-4eba-bb63-0a50b3c184cc.flac][(audio)]]过去，家务事总是由妻子一个人来做，[[file:8886faff-41c9-45d9-b921-f50d45221dde.flac][(audio)]]现在丈夫在家也要发挥“半边天”的作用。[[file:666b4d9e-e884-473a-a1fc-3ecf3fdffcef.flac][(audio)]]很多家庭的家务事都有了分工：[[file:e7c3677a-d79d-4034-a489-c6dab1844e73.flac][(audio)]]常常是丈夫买菜，妻子做饭；[[file:d08324ec-2e87-49d4-af26-9cfa23370e8a.flac][(audio)]]丈夫打扫房间，妻子洗衣服；[[file:a78791d8-f148-4a4c-99f4-1277420f7c6b.flac][(audio)]]丈夫管孩子学习，妻子管孩子的吃穿。[[file:02d526e6-c209-4f47-b6ef-312201bec64d.flac][(audio)]]有的外国朋友看到中国男人会做菜，[[file:da28669e-e223-4521-9688-49b8e289ee03.flac][(audio)]]觉得很奇怪。[[file:283e38bf-fa6e-4c71-baf9-7dee59a03bc4.flac][(audio)]]要是你生活在中国人的家里，[[file:5df7b789-9099-4b62-92bc-f5a783e031d0.flac][(audio)]]就会发现丈夫每天也要下厨房，[[file:967c4b28-36c2-4177-9762-a42580434515.flac][(audio)]]他们的做菜技术就是这样练出来的。[[file:14d307ae-0826-4936-97c5-ea099aac3de5.flac][(audio)]]当然，总的来说家务事儿妇女要比男人干得多，[[file:c47ca742-6f41-49de-828e-ea9d6f5f881e.flac][(audio)]]而且不做家务的丈夫现在也还有。[[file:7fe8cdb0-1507-42da-b4b4-a1553f0be649.flac][(audio)]]

第三呢，是职业妇女的困难。[[file:1d0465d9-7e5e-4cde-9adb-92d9134b97d1.flac][(audio)]]职业妇女在外边担负一定的工作，[[file:56d8d19e-da6a-4eb9-8a7f-24c9b9cedadc.flac][(audio)]]在家里又担负很重的家务。[[file:7c56c89e-34bc-4d22-9cb7-cab4508f0dc4.flac][(audio)]]她们既要做一个好的工作人员，[[file:1f474480-84d5-4f7b-91f2-49936bf0dbf4.flac][(audio)]]又要做一个好妻子、好母亲，[[file:7f47f195-d99c-41ac-b39a-3e6d99efbe4a.flac][(audio)]]所以生活很不容易，比男人辛苦得多。[[file:c649ca3e-7cda-4af7-a243-b80589502c15.flac][(audio)]]有的女职工说，一天二十四小时，[[file:0e0c7849-2d29-4cc2-916a-de82c1709832.flac][(audio)]]除了吃饭睡觉以外，[[file:9c997cfa-d8b4-4c21-82cf-17902a1bcd75.flac][(audio)]]几乎没有一分钟是她自己的！[[file:561adce8-ada0-46c9-a1da-6b47ba8f863d.flac][(audio)]]她们没有时间学习，没有休闲活动。[[file:dcf54823-c601-4445-9bf6-a23d8691a069.flac][(audio)]]家庭和事业的矛盾是职业妇女很难解决的问题。[[file:57bba470-78c2-42ea-b382-f160a8e8e196.flac][(audio)]]

最后我要谈的问题是，[[file:a430ae67-dbe8-4377-9db0-49e87d62bdbb.flac][(audio)]]现在男女已经平等了吗？[[file:f95678e4-9adf-4524-b29b-e3d91afe8dcd.flac][(audio)]]

很多中国妇女认为，[[file:0e6fa07b-a7aa-4f15-9875-9e60b9c89e35.flac][(audio)]]现在在一些方面还没有完全实现男女平等。[[file:29c99878-dece-4a0e-b3ba-eebd883436b1.flac][(audio)]]比如在就业方面，[[file:3b505cba-8dd2-4ba4-8a7e-be5fb2f6db7d.flac][(audio)]]有的地方对妇女还很不公平，[[file:4d3a0812-c7b9-488c-a161-3ea6af52d00a.flac][(audio)]]妇女做同样的工作，[[file:32620402-c2b4-4df2-83ed-a5384127a9ce.flac][(audio)]]得到的报酬没有男人高。[[file:836963e0-8bdf-472b-abf6-d3a27af372eb.flac][(audio)]]在一些农村，[[file:f4ebfe32-2f3a-47fc-acb4-90ee33a44bfa.flac][(audio)]]女孩受教育的机会比男孩少得多；[[file:177c4304-eb36-4553-8669-0ac20c38c339.flac][(audio)]]在科学家、教授、经理中，妇女还非常少。[[file:175040b0-2fa7-4d5e-8590-900198ff09c6.flac][(audio)]]这些情况不但中国有，[[file:b7eb1f61-6730-4510-97b6-de7f69ec9081.flac][(audio)]]世界很多地方也都有。[[file:bbf0e666-f218-474a-9c9f-dc4333b92656.flac][(audio)]]总的来说，为了完全实现男女平等，[[file:09bb8ca5-37d1-4671-841b-ba1883122519.flac][(audio)]]我们还有很长的路要走。[[file:e6f70779-7b93-4748-b7b5-abe80bd47338.flac][(audio)]]

谢谢，大家。[[file:d9d09829-fc6a-47ae-95e1-97003cf76857.flac][(audio)]]

**** 生词
:PROPERTIES:
:NOTETYPE: 2428d9df-45bc-4c06-806a-8e4536124689
:END:

***** 1
:PROPERTIES:
:ID: f6c41cb6-0825-47a0-9012-b9c100dfeea8
:END:

****** 简体字

地位

****** 词性

N

****** 拼音

dìwèi

****** 西语翻译

posición, puesto

****** 音频

55bea325-138b-42b6-8d27-ea581e2a236d.mp3

***** 2
:PROPERTIES:
:ID: cfa502e8-16e5-4b73-a650-cb3963fc9c2d
:END:

****** 简体字

担负

****** 词性

V

****** 拼音

dānfù

****** 西语翻译

asumir, encargarse, hacerse cargo

****** 音频

726d27f2-9246-4204-8dd3-24111544bc2e.mp3

***** 3
:PROPERTIES:
:ID: 4b818c0e-68cf-4088-9ee7-f55c4f2cf937
:END:

****** 简体字

占

****** 词性

V

****** 拼音

zhàn

****** 西语翻译

ocupar

****** 音频

85f156e3-32cf-4e4d-a4be-94354522ebfd.mp3

***** 4
:PROPERTIES:
:ID: 4e490526-5d02-4902-904f-f9ec590441a0
:END:

****** 简体字

部长

****** 词性

N

****** 拼音

bùzhǎng

****** 西语翻译

ministro

****** 音频

dd1f0557-a378-420b-9933-d252fabadf3d.mp3

***** 5
:PROPERTIES:
:ID: 0e04161b-6f4d-422e-8bfa-1fbc51b468ce
:END:

****** 简体字

纺织

****** 词性

V

****** 拼音

fǎngzhī

****** 西语翻译

textil

****** 音频

69deacef-bf7b-4876-9429-a098cda9734d.mp3

***** 6
:PROPERTIES:
:ID: a9c7c26a-e07c-466c-acda-e7f828bf20c1
:END:

****** 简体字

工人

****** 词性

N

****** 拼音

gōngrén

****** 西语翻译

trabajador

****** 音频

0214af66-3453-4fe1-bf79-1c6d81d75d94.mp3

***** 7
:PROPERTIES:
:ID: f05803b4-6aa2-437b-970c-a0eeb2d8b9e7
:END:

****** 简体字

护士

****** 词性

N

****** 拼音

hùshi

****** 西语翻译

enfermera

****** 音频

bf93f904-e0af-4b32-ad36-10f78ced7799.mp3

***** 8
:PROPERTIES:
:ID: 4905ea38-bf71-46cc-a97f-34eb9c9f2343
:END:

****** 简体字

封建

****** 词性

N

****** 拼音

fēngjiàn

****** 西语翻译

feudalismo

****** 音频

3a17635a-25f6-4828-aab4-1a9bd8469254.mp3

***** 9
:PROPERTIES:
:ID: 7a728077-d9a8-4238-baa7-f175f60b9bdb
:END:

****** 简体字

服从

****** 词性

V

****** 拼音

fúcóng

****** 西语翻译

obedecer

****** 音频

39a1a32a-762c-4cb8-8afb-764b988f37e1.mp3

***** 10
:PROPERTIES:
:ID: 6c4b94a7-f5eb-467e-a9db-2923dd1dac62
:END:

****** 简体字

事业

****** 词性

N

****** 拼音

shìyè

****** 西语翻译

causa, empresa, obra, trabajo

****** 音频

d6ec367c-4cfc-4df2-86c5-8ce023734f26.mp3

***** 11
:PROPERTIES:
:ID: c8352181-da42-490c-b6cc-5002718acd34
:END:

****** 简体字

矛盾

****** 词性

N

****** 拼音

máodùn

****** 西语翻译

contradicción

****** 音频

069b8a9a-ea66-45e1-8f2f-795f6fe978ac.mp3

***** 12
:PROPERTIES:
:ID: b96ca4a6-9a9b-41bc-a7e9-8e978e9e7ace
:END:

****** 简体字

完全

****** 词性

Adv.

****** 拼音

wánquán

****** 西语翻译

totalmente

****** 音频

bf3c8449-0379-4522-907a-c5c8a68555f1.mp3

***** 13
:PROPERTIES:
:ID: dfa9b983-61c2-43ab-8d3b-560848d2ff5c
:END:

****** 简体字

报酬

****** 词性

N

****** 拼音

bàochou

****** 西语翻译

pago, recompensa, remuneración

****** 音频

e0e159b1-1508-4f2d-ac89-502fae7864b3.mp3

** 三、练习与运用

*** 重点句式
:PROPERTIES:
:NOTETYPE: fa9400e9-3a6f-4873-977c-43bc9382b00a
:END:

**** 1
:PROPERTIES:
:ID: db3fa74f-a915-40a0-8d66-574435aca3c2
:END:

***** 句子

城市里几乎都是双职工的家庭。

***** 音频

bae55cde-2d35-4f30-aa2b-3c1832291ed9.mp3

**** 2
:PROPERTIES:
:ID: ad18aa99-0c9e-4867-9deb-9c1e9d3d8231
:END:

***** 句子

为了解决就业问题，就必须让妇女回家吗？

***** 音频

c154cd01-c654-46ff-9ddd-9eeed62edf15.mp3

**** 3
:PROPERTIES:
:ID: 0075597c-59b8-476f-ab2c-687f9ef10a02
:END:

***** 句子

在全中国的职工中，女职工占百分之四十。

***** 音频

76b1bf53-b21c-4ee2-b33e-6970a04dd46a.mp3

**** 4
:PROPERTIES:
:ID: c7f97fd4-e106-44be-890c-3dccbfac0b97
:END:

***** 句子

没有一个母亲不关心自己的孩子

***** 音频

dc1c81cb-18d1-49c6-a166-48257effd1c2.mp3

**** 5
:PROPERTIES:
:ID: 4f85bac1-c636-478f-a893-13bac576528f
:END:

***** 句子

只有在各个方面男女都享受同样的权利，男女才能平等。

***** 音频

7983636c-c7a8-4ed2-9d81-aad88efbf4cb.mp3

**** 6
:PROPERTIES:
:ID: 804e11f6-9e8b-4c98-a087-ed5ec50a3fce
:END:

***** 句子

要是你生活在中国人的家里，就会发现丈夫每天也要下厨房。

***** 音频

fcaf9c29-61cc-44eb-9771-8e71814317ac.mp3

*** 2. 句子练习

**** A

***** 几乎
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: 22d4ce67-0fcc-41a6-ba12-f0e002a515b9
:END:

******* 句子填空

昨天去看足球比赛的人多级了，我们班的同学🟦。

******* 词语

去

******* 答案

几乎都去

****** 2
:PROPERTIES:
:ID: a62c1632-208e-4a84-9268-a5bd559a996b
:END:

******* 句子填空


在我们的学校，教外语的老师🟦。
******* 词语

女的

******* 答案

几乎都是女的

****** 3
:PROPERTIES:
:ID: 9ac3e4e5-2049-41dd-8abd-020517b2b513
:END:

******* 句子填空

为了买房子，他🟦把一辈子的积蓄🟦。

******* 词语

花

******* 答案

******** Part 1

几乎

******** Part 2

花完了

****** 4
:PROPERTIES:
:ID: 3629087b-5bd9-4d2d-bacd-eef717f70263
:END:

******* 句子填空

现在的城里人🟦，男的女的都忙工作，实在没有很多时间照顾家庭。

******* 词语

双职工

******* 答案

几乎都是双职工

****** 5
:PROPERTIES:
:ID: 70720001-905a-4e64-93d0-8e3609f21b68
:END:

******* 句子填空

星期六回北京的车票很不好买，我🟦。

******* 词语

回不去

******* 答案

几乎回不去

***** 为了
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: a5b484f0-edb4-4cb9-b09f-ff11a7718814
:END:

******* 句子填空

🟦，妇女就应该回家做家务吗？

******* 词语

就业

******* 答案

为了解决男女就业问题


****** 2
:PROPERTIES:
:ID: 99eafd1c-acf5-4eb1-b094-60c5a35ffa59
:END:

******* 句子填空

🟦，马大为决定来中国留学。

******* 词语



******* 答案



****** 3
:PROPERTIES:
:ID: 124e76dc-1b5d-4f30-81f7-e82dc52c42ce
:END:

******* 句子填空

🟦，他们都 在认真准备。

******* 词语

比赛

******* 答案



****** 4
:PROPERTIES:
:ID: b84d0cb2-4c30-4ec0-b35b-540dfaf3272e
:END:

******* 句子填空

🟦，我们就应该更快地发展都育事业。

******* 词语

经济

******* 答案



****** 5
:PROPERTIES:
:ID: 1a53a1fe-be0e-4b59-8316-b740332fe29d
:END:

******* 句子填空

🟦，我们都要重视环境保护的工作。

******* 词语

人类自己

******* 答案



***** 在……方面
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: 0a93f058-ace9-4881-9b72-9d16447ed2ae
:END:

******* 句子填空

🟦，老师和同学对我帮助很大，所以我的口语进步很快。

******* 词语

no value

******* 答案



****** 2
:PROPERTIES:
:ID: eb9999c7-a970-4459-83e2-788f400b5ec0
:END:

******* 句子填空

🟦，问题不大，我已经向银行贷款了。

******* 词语



******* 答案



****** 3
:PROPERTIES:
:ID: 32c302e6-702f-4124-b0fc-61c4dea2db3e
:END:

******* 句子填空

🟦，主要由她丈夫管，她只管孩子的吃穿。

******* 词语



******* 答案



****** 4
:PROPERTIES:
:ID: 052ee45e-414a-43f3-bdaa-7ecccfe7b21e
:END:

******* 句子填空

🟦，男女还不完全平等，有些工作女的也可以做，可是他们不用女的，只用男的。

******* 词语



******* 答案



****** 5
:PROPERTIES:
:ID: 02a30926-1dc3-4847-aada-755b88a48c46
:END:

******* 句子填空

🟦，妇女比男人的机会少得多。

******* 词语



******* 答案

***** 在……中

****** 词语

******* 1

买习


******* 2

沙漠


******* 3

婚礼


******* 4

事业


******* 5

所有职工

****** 题目

******* 1

******** 句子填空

🟦，几乎看不到植物。

******** 答案

在沙漠中

******* 2

******** 句子填空

🟦，新娘常常要向客人敬酒。

******** 答案

在婚礼中

******* 3

******** 句子填空

🟦，她常重到公司老板的夸奖。

******** 答案

在实习中

******* 4

******** 句子填空

🟦，男的常常比女的多。

******** 答案

在所有职工中

******* 5

******** 句子填空

🟦，他们互相帮助、互相合作。

******** 答案

在事业中

* 第41课

** 一、课文

*** 一

**** 内容
:PROPERTIES:
:NOTETYPE: aabca9f4-d7dc-4ae0-a92d-5187b3b41b52
:END:

王小云：宋华，毕业以后，[[file:966d7eb7-336c-4959-b71f-e8f6430f3dd4.flac][(audio)]]你打算干什么？[[file:bafe26c9-92d9-455c-9062-061676da25a2.flac][(audio)]]

宋华：我想先去一个律师事务所干几年，[[file:86c53557-9661-4aff-ba62-55275855bb40.flac][(audio)]]熟悉熟悉这方面的情况，[[file:d676090f-67e2-43c2-a38a-6816b053586b.flac][(audio)]]然后自己开个律师事务所。[[file:a5986f69-a61f-442c-9451-0a197733b065.flac][(audio)]]

王小云：这个想法很好啊。[[file:b39c015a-e5ca-45a8-ae3e-734be284a8fa.flac][(audio)]]在咱们国家，[[file:136cf1ae-1d98-4c9a-bac9-9420a5e0565d.flac][(audio)]]律师算是很新的职业。[[file:564545d9-e53e-4e0e-b911-bfb0fb84fc41.flac][(audio)]]有不少人还很怕打官司，[[file:78ffa49f-4941-4bb2-99f5-727c59839ad8.flac][(audio)]]他们也不太了解[[file:716f4b0d-747b-44ec-9246-3557ed5d783b.flac][(audio)]]怎样请律师帮助自己打官司。[[file:a39b45a5-2e6d-4853-8b59-3df5b0464010.flac][(audio)]]不过，现在大家已经开始注意[[file:ed41ada9-6e3b-428f-b969-fc08687fa012.flac][(audio)]]用法律来保护自己的权利了，[[file:ecb92818-a059-424e-b630-dc2db0fc39e2.flac][(audio)]]我想人们会越来越需要律师。[[file:784416e0-fd6a-416e-b178-1da6415e5774.flac][(audio)]]

宋华：可是我爸爸的看法就不一样。[[file:119fc335-835a-42f0-9bc9-526d50795ecd.flac][(audio)]]他认为我应该去考国家公务员，[[file:1613d400-1db9-43c3-860f-f2746d46bf7a.flac][(audio)]]到政府部门工作，[[file:925176ab-2e8a-47cf-8eef-b46efdc4893c.flac][(audio)]]我妈妈也让我到国营公司找个工作，[[file:75d4bc29-00b2-47c8-b0d5-48b7a23a0775.flac][(audio)]]他们都不同意我当律师。[[file:6f2f3300-3cea-44d9-84b6-a70d137d31fe.flac][(audio)]]他们说律师靠帮别人打官司挣钱，[[file:b10de59b-1bd2-4d2a-98c6-16e9cf1e4cd7.flac][(audio)]]不像公务员那样，[[file:ee2f957e-2fd9-4d54-8f8e-615558c93f16.flac][(audio)]]有稳定的收入。[[file:2f1e9dbf-cecd-4f90-8e68-8b206e30f0dc.flac][(audio)]]

王小云：对，我想起来了，[[file:5d93e63c-279f-4317-960b-a3ba30b8b303.flac][(audio)]]上次去你家的时候，[[file:dc1b29c6-944e-4fbe-9b4f-2c784325cc2f.flac][(audio)]]他们说过这个意思。[[file:a1392fe5-ce5c-4b4a-8239-8f796f79cac4.flac][(audio)]]你同意这种看法吗？[[file:78957504-787d-45be-900a-ae71b0246b18.flac][(audio)]]

宋华：当然不同意。[[file:73c49c97-f46c-4fec-a053-0bd5d1446ddf.flac][(audio)]]我爸爸希望我找个稳定的工作，[[file:4c1cb21a-e6a0-436b-b044-486a83b75b3b.flac][(audio)]]也就是说，拿国家的工资，[[file:4ff59436-2ce9-4b58-bbca-1e6867c4fdfb.flac][(audio)]]平平安安地过日子。[[file:c803e65f-d41b-490f-ac97-efea48b3d4f2.flac][(audio)]]

王小云：他们那一代人，[[file:c4f38188-0ec2-4779-ab4e-2b52b9235ea4.flac][(audio)]]大学毕业以后都由国家分配工作。[[file:47e792ac-b640-457b-b75d-255765c1f2bc.flac][(audio)]]国家让你去哪儿就去哪儿。[[file:038dce2a-7439-4014-92e6-ad6d461788bf.flac][(audio)]]即使自己有些想法，[[file:866c5c37-56c2-459e-9c1b-c1bde67f0758.flac][(audio)]]也得服从国家分配。[[file:d0f6c5a7-0512-49dc-a0a5-2f37f6280a7f.flac][(audio)]]

宋华：确实是这样。[[file:58b33863-c85e-4ab0-9896-03bb0b526e4e.flac][(audio)]]关于就业的问题，[[file:0b9237c5-cf95-41db-a039-582b9ba9b147.flac][(audio)]]我们跟上一代人的想法不一样，[[file:41ac28d0-1785-4139-a7a7-c80662c27fd6.flac][(audio)]]我们首先想到怎样去做自己喜欢的工作，[[file:47cd937e-d7cd-41ed-8779-7a8d30c5bc8e.flac][(audio)]]能不能实现自己的理想。[[file:3b1c9f14-dfd1-4415-97ea-13a8a32212a0.flac][(audio)]]我们希望生活中有挑战，[[file:12742bb9-2502-449c-a3fb-e34bef5e3d1f.flac][(audio)]]工作中有竞争。[[file:0147aaa2-ea4e-4793-9c1f-a4cd53a80ef4.flac][(audio)]]

王小云：还有，能得到比较满意的收入。[[file:673532d2-a878-425b-b34b-a1ac82969462.flac][(audio)]]

宋华：对。[[file:437b27db-4620-4d98-8b94-f264083d173c.flac][(audio)]]我爸爸妈妈听说我打算以后自己开事务所，[[file:67e62b48-2196-4659-967b-9c7066bdc91b.flac][(audio)]]就更着急了。[[file:b2f5a60f-d317-4947-a469-6d9d297f6533.flac][(audio)]]

王小云：不管老人怎么看，[[file:ebefd1ad-251e-4bb5-8ec6-17969ff55c0b.flac][(audio)]]你都应该努力实现自己的理想。[[file:66c2d1a1-dca1-4407-a641-b7852e97b2cd.flac][(audio)]]

宋华：那当然。[[file:d93edc3c-84d3-405e-9f38-9b7455f62dcc.flac][(audio)]]现在企业和公司也都需要有自己的律师，[[file:c2cc8732-0fcd-4f3b-80d0-e6187f1fae16.flac][(audio)]]所以律师这个职业[[file:fa26dcb7-6916-47d3-8492-1ae718eeff8b.flac][(audio)]]一天比一天受欢迎。[[file:56e6660e-422a-4a2d-8557-e492f12bd72c.flac][(audio)]]我想只要努力工作，[[file:c8fc6735-c3fb-4846-8b9c-b4bd61cd6ec1.flac][(audio)]]就一定会有一个好的前途。[[file:85d8f647-e87f-416e-bc01-d970a731f78c.flac][(audio)]]小云，你有什么打算？[[file:ab60eaed-19c8-482d-88c6-1c69efecd7a3.flac][(audio)]]

王小云：我打算先考研究生。[[file:e6f480a0-0357-44f4-a53f-38f53861d4fd.flac][(audio)]]不过，现在我还没有决定。[[file:f8fa737e-3615-4732-baf6-fb1dee0da298.flac][(audio)]]要是有合适的工作，[[file:7195e660-382d-4948-917b-3f7ea4fd7058.flac][(audio)]]我就先干起来。[[file:630d28ec-1bfb-48a5-86f0-7089618603c5.flac][(audio)]]

**** 生词
:PROPERTIES:
:NOTETYPE: 2428d9df-45bc-4c06-806a-8e4536124689
:END:

***** 1
:PROPERTIES:
:ID: 3284562d-6cd1-4e45-bc91-757242e423a5
:END:

****** 简体字

律师

****** 词性

N

****** 拼音

lǜshī

****** 西语翻译

abogado

****** 音频

6833c349-1c55-441a-84ac-0cc88c04459b.mp3

***** 2
:PROPERTIES:
:ID: 6891f23a-97f4-4b78-8e86-5b3f5a972aa7
:END:

****** 简体字

事务所

****** 词性

N

****** 拼音

shìwùsuǒ

****** 西语翻译

bufete, oficina

****** 音频

11e462d9-3976-4cbf-adea-675efa1d1246.mp3

***** 3
:PROPERTIES:
:ID: 59b8f275-9be8-4918-bf76-8199585fa9c7
:END:

****** 简体字

熟愁

****** 词性

V

****** 拼音

shúxi

****** 西语翻译

trabajo, tarea, asunto

****** 音频

e6eadf67-5f9b-4781-bb87-2a7eba00411c.mp3

***** 4
:PROPERTIES:
:ID: dbf400b5-7dc3-4f9f-908f-75ca8cbd2ea6
:END:

****** 简体字

想法

****** 词性

N

****** 拼音

xiǎngfǎ

****** 西语翻译

idea, opinión, pensamiento

****** 音频

14edd7e8-bd49-4d66-96bb-26b205c759d0.mp3

***** 5
:PROPERTIES:
:ID: 00ff12f9-0451-44fa-9dfd-58dede5ae13f
:END:

****** 简体字

打官司

****** 词性

V O

****** 拼音

dǎ guānsi

****** 西语翻译

litigar, entablar un pleito contra alguien

****** 音频

553dc666-6289-4543-8489-b2d59fdbee5e.mp3

***** 6
:PROPERTIES:
:ID: 80ffd2b7-5e23-4550-ba18-a022d3009092
:END:

****** 简体字

法律

****** 词性

N

****** 拼音

fǎlǜ

****** 西语翻译

ley

****** 音频

410a1753-6476-4181-ac2d-732792478756.mp3

***** 7
:PROPERTIES:
:ID: d300f308-9199-456f-8345-831c993e01d4
:END:

****** 简体字

需要

****** 词性

V

****** 拼音

xūyào

****** 西语翻译

necesitar, requerir

****** 音频

3d532bed-bf5b-49a0-a39e-f3b47e9ca113.mp3

***** 8
:PROPERTIES:
:ID: 269ba69d-dda0-48eb-b234-367bb75e4260
:END:

****** 简体字

公务员

****** 词性

N

****** 拼音

gōngwùyuán

****** 西语翻译

funcionario del estado, público

****** 音频

6bdbbeb0-2108-447a-94d8-4e9c281e135f.mp3

***** 9
:PROPERTIES:
:ID: 4073d76d-ff77-490e-9659-797f06df8d83
:END:

****** 简体字

国营

****** 词性

A

****** 拼音

guóyíng

****** 西语翻译

de la administración estatal

****** 音频

16be7ae0-f282-4c1e-8fcf-be43f9ac2cef.mp3

***** 10
:PROPERTIES:
:ID: 3032195c-9fe5-4976-b2a7-d610a0f8a6c9
:END:

****** 简体字

同意

****** 词性

V

****** 拼音

tóngyì

****** 西语翻译

estar de acuerdo

****** 音频

ac89ffe7-ee9e-4049-9702-7b78993b95f1.mp3

***** 11
:PROPERTIES:
:ID: 4dc28dcc-190b-44a1-8b3b-d26a9253d938
:END:

****** 简体字

靠

****** 词性

V

****** 拼音

kào

****** 西语翻译

depender de, apoyarse en

****** 音频

6961a291-0b19-4f77-9135-81b2323f20e5.mp3

***** 12
:PROPERTIES:
:ID: 6e4f9fe9-855f-46fc-95b2-f1a6199115b5
:END:

****** 简体字

平安

****** 词性

A

****** 拼音

píng’ān

****** 西语翻译

sano y salvo, sin contratiempos

****** 音频

b9311750-29f2-4b65-b2f5-20cc794f57da.mp3

***** 13
:PROPERTIES:
:ID: af7a0b63-a2d7-44a3-aece-a88b70f29fcd
:END:

****** 简体字

代

****** 词性

N

****** 拼音

dài

****** 西语翻译

generación

****** 音频

5c879ecc-ca88-4f4d-85dc-536eae5c8e0b.mp3

***** 14
:PROPERTIES:
:ID: 105c67a9-d4aa-4ff6-8ff0-b4e3df0bc98b
:END:

****** 简体字

分配

****** 词性

V

****** 拼音

fēnpèi

****** 西语翻译

distribuir

****** 音频

a2b255a9-76b5-4cca-960e-7cc66655f185.mp3

***** 15
:PROPERTIES:
:ID: 9b276641-dced-41d0-b86e-a9aec3a4ff25
:END:

****** 简体字

即使

****** 词性

Conj.

****** 拼音

jíshǐ

****** 西语翻译

aunque, a pesar de

****** 音频

4530cbba-0715-48dd-9649-fe4a3e484ab7.mp3

***** 16
:PROPERTIES:
:ID: 9d071204-f40d-4266-9c25-62b33f2489e0
:END:

****** 简体字

关于

****** 词性

Prep.

****** 拼音

guānyú

****** 西语翻译

sobre

****** 音频

77180974-ff09-4821-be00-ddb2387bbe7d.mp3

***** 17
:PROPERTIES:
:ID: 75572792-17d4-4601-8b7a-32adb5c5ce48
:END:

****** 简体字

挑战

****** 词性

V

****** 拼音

tiǎozhàn

****** 西语翻译

desafiar

****** 音频

460bd094-dd4f-4efb-92f0-e93a7ddc3bc8.mp3

***** 18
:PROPERTIES:
:ID: 3bbf663f-49d6-4805-8753-3ff94fdd5fac
:END:

****** 简体字

满意

****** 词性

A

****** 拼音

mǎnyì

****** 西语翻译

satisfecho, contento

****** 音频

3785080f-e25d-43c0-b34c-410cb9767a48.mp3

***** 19
:PROPERTIES:
:ID: b395c668-a30d-42b0-acd9-8bc363d0f9ab
:END:

****** 简体字

不管

****** 词性

Conj.

****** 拼音

bùguǎn

****** 西语翻译

no importa (qué, cómo, etc.), sea lo que sea

****** 音频

6f6fdc6e-c9ef-4d7c-9051-2bc9bc779c77.mp3

***** 20
:PROPERTIES:
:ID: b090d692-db92-4d67-8337-1c6b57a7da0c
:END:

****** 简体字

前途

****** 词性

N

****** 拼音

qiántú

****** 西语翻译

futuro, perspectiva

****** 音频

0ef022f0-e54a-4789-b8e7-248c36974c43.mp3

