* 第39课

** 三、练习与运用

*** 2. 句子练习

**** A

***** 总（是）
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: c7ad2028-911b-4a2a-888a-e831ead2bfd5
:END:

******* 句子填空

他对工作很不认真，你每次找他帮助解决问题，他🟦。

******* 词语

说要研究研究

******* 答案

总是说要研究研究

****** 2
:PROPERTIES:
:ID: 14b8aa6a-ef2f-439a-8c98-b18558c9961f
:END:

******* 句子填空

他学习很努力，也很认真，他的成绩🟦。

******* 词语

全班第一

******* 答案

总是全班第一

****** 3
:PROPERTIES:
:ID: fd33e2d8-934d-4bea-abe8-ec80dd3afd14
:END:

******* 句子填空

北京王府井大街🟦。

******* 词语

那么热闹

******* 答案

总是那么热闹

****** 4
:PROPERTIES:
:ID: eea493f1-f6ae-4e8d-a670-48a46cef9325
:END:

******* 句子填空

他们俩在食堂🟦，别人听了觉重很别扭。

******* 词语

大声地说笑

******* 答案

总是大声地说笑

****** 5
:PROPERTIES:
:ID: 9e0cc156-23c4-4bdc-a045-ba043b71b9e1
:END:

******* 句子填空

他去了好几次北京，🟦。

******* 词语

没时间登长城

******* 答案

总也没时间登长城

***** 终于
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: 14d2bac4-72dd-4785-bfe7-b75b4e78938c
:END:

******* 句子填空

这么多的作业，他🟦。

******* 词语

做完

******* 答案

终于做完

****** 2
:PROPERTIES:
:ID: 92d8657b-a8cc-4a5c-a51b-dc685ea97bbd
:END:

******* 句子填空

他很早就想买这本书，今天他🟦。

******* 词语

买到

******* 答案

终于买到

****** 3
:PROPERTIES:
:ID: e44427c2-4179-4f83-9a0f-4edd01aafb9d
:END:

******* 句子填空

这个问题已经研究好几次了，这次🟦

******* 词语

把它解决

******* 答案

终于把它解决

****** 4
:PROPERTIES:
:ID: c6e1275a-b612-4c1a-b4f9-90137285de22
:END:

******* 句子填空

他很早就想参翙兵马俑，今天来西安旅游，他🟦。

******* 词语

看到

******* 答案

终于看到了

****** 5
:PROPERTIES:
:ID: 5cf8cd9f-53b2-4e68-99c5-42234a433365
:END:

******* 句子填空

他打扫了一个上午，房间🟦。

******* 词语

干净

******* 答案

终于干净了

***** 必须（不必）
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: c18d20bf-f394-4106-868d-ccc6e63c75bf
:END:

******* 句子填空

我们🟦以前到火车站，才能坐上今天八点一刻去广州的火车。

******* 词语

no value

******* 答案



****** 2
:PROPERTIES:
:ID: ec926a8a-1142-44f7-81f6-90cfb3fb1a47
:END:

******* 句子填空

你🟦，才能学好外语。

******* 词语

no value

******* 答案



****** 3
:PROPERTIES:
:ID: d1a040c1-96ff-4c7f-901d-aae03925d8a8
:END:

******* 句子填空

小燕子说🟦，才能当大饭店里的厨师。

******* 词语

no value

******* 答案



****** 4
:PROPERTIES:
:ID: 608e1628-3e64-4299-ae1c-0ff5a9284152
:END:

******* 句子填空

车开不上去了，🟦。

******* 词语

no value

******* 答案



****** 5
:PROPERTIES:
:ID: 88fedf8e-b9fb-4b72-95cf-cc7b0364b9a5
:END:

******* 句子填空

您🟦那么着急，他们一定会帮助您解决问题的。

******* 词语

no value

******* 答案



***** 究竟
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: 384db21d-a177-45bf-bfe0-440b70c7dd7d
:END:

******* 句子填空

他们提的意见🟦？

******* 词语

对

******* 答案



****** 2
:PROPERTIES:
:ID: 0170bd5a-1b26-47c3-b065-f66f14f8acfa
:END:

******* 句子填空

小燕子做的菜🟦？

******* 词语

好吃

******* 答案



****** 3
:PROPERTIES:
:ID: e7d3ef02-ad39-4613-8f4f-016e82f5b1b6
:END:

******* 句子填空

我们班🟦？

******* 词语

考口语

******* 答案



****** 4
:PROPERTIES:
:ID: 17d08637-7741-43fc-84ee-5c701523b5d7
:END:

******* 句子填空

他🟦？

******* 词语

参加比赛

******* 答案



****** 5
:PROPERTIES:
:ID: ed4b8ae9-6cd5-43ad-a6b5-97c09f7a6827
:END:

******* 句子填空

张经理🟦？

******* 词语

回公司

******* 答案



* 第40课

** 一、课文

*** 一
:PROPERTIES:
:NOTETYPE: aabca9f4-d7dc-4ae0-a92d-5187b3b41b52
:END:

陆雨平：有人提出妇女结婚以后，[[file:306cbb4a-ca58-441d-bdec-7c303557483b.flac][(audio)]]特别是有了孩子以后，[[file:f494eba3-293c-4845-a4c1-c41169ff9fd7.flac][(audio)]]应该回到家里做“全职太太”，[[file:f16dcf60-3ddb-47b5-8450-a8903e0b4b37.flac][(audio)]]因为她们要照顾孩子，[[file:05cc2c96-a89a-4ee4-99d8-572ad85a0810.flac][(audio)]]要做家务。[[file:4e904cf4-7ec8-4586-9285-a0d30ee74c7a.flac][(audio)]]对这个问题，[[file:48946a2b-b554-40da-b50b-429544523b0c.flac][(audio)]]你们有什么看法？[[file:7f509a91-92df-4581-bc51-7a480f1c22e6.flac][(audio)]]

陈老师：这个主意很可能是男人想出来的吧？[[file:ee046613-e51e-4131-a17a-27a50cf00761.flac][(audio)]]妇女经过了多少个世纪的努力，[[file:2c887647-fcf8-47f7-a304-d3120e9111a8.flac][(audio)]]终于从家里走出来，[[file:4b00b6b0-3dcd-4cbe-aaaa-d0b3dac4ebea.flac][(audio)]]得到工作的权利，[[file:f5b8b959-cd5d-421c-a257-553afa3f6293.flac][(audio)]]而且能发挥“半边天”的作用。[[file:23f6bc68-ac31-4ec9-afe0-a2e24cd4c248.flac][(audio)]]这是社会的进步。[[file:d6064e1e-bbc6-417b-9fe0-448ddadfa6d3.flac][(audio)]]现在怎么又要让妇女回到厨房去呢？[[file:3a59f2b6-66e9-4228-a33c-6b1701698599.flac][(audio)]]

陆雨平：这不只是一些男人的看法，[[file:bd3c8b1a-0037-435e-a18a-a7d2c653b559.flac][(audio)]]有些妇女也有这样的看法。[[file:4007597d-06a8-422b-8a35-e7264421b8b7.flac][(audio)]]大家都知道，[[file:de577a22-8b3d-453a-9d15-177a5ae0016a.flac][(audio)]]城市里几乎都是双职工的家庭，[[file:114550a1-c859-4e90-916e-44298ae88a45.flac][(audio)]]丈夫和妻子每天都要在外边工作，[[file:17bbe1c0-cc1a-4f41-950a-85bd1b86b094.flac][(audio)]]他们没时间照顾孩子。[[file:04be9a92-2363-4177-a36e-e7e26bec5770.flac][(audio)]]没有一个母亲不关心自己的孩子，[[file:6b30601c-247b-4381-87d4-ff770cd896ab.flac][(audio)]]要是妇女回家，[[file:d6e7dbb6-091c-4bcc-aa52-aa674af61907.flac][(audio)]]孩子的教育问题就可以解决得更好。[[file:3672997a-9c8d-474c-8d4d-49475e74e90d.flac][(audio)]]这不是看不起妇女，[[file:2c7ddef3-1b06-47a9-bba2-358000220543.flac][(audio)]]而是为了更好得发挥妇女的作用。[[file:e43b5d8e-be9e-4d86-b669-444d2483723f.flac][(audio)]]

王小云：我认为，照顾孩子和做家务[[file:eabbffed-ff1a-4b32-9d9f-ae9c59632f25.flac][(audio)]]不只是妇女的事儿，[[file:d0d3d664-1d74-4ef7-9888-55e68d901c30.flac][(audio)]]也是男人的事儿。应该 男女都一样：[[file:f737aad9-2407-4fab-b711-164e134f132b.flac][(audio)]]要是愿意回家照顾孩子，就回家照顾孩子；[[file:4ac05c5b-7c8f-40fa-9842-f0850050aa64.flac][(audio)]]要是愿意出来工作，就出来工作。[[file:7fae16e3-6745-480e-99eb-50465027760f.flac][(audio)]]

陆雨平：如果大家都愿意回家照顾孩子，[[file:836a5c32-173c-4548-bad7-c0794a545e78.flac][(audio)]]不愿意出来工作，怎么办？[[file:10565814-9524-4ccf-ac36-8fdf30bc9c72.flac][(audio)]]

王小云：这不可能。不会没有人愿意出来工作。[[file:486a9ae1-928b-48ff-b34b-201c4773a0a9.flac][(audio)]]

陆雨平：有人还认为，中国人口太多，[[file:ac516d51-e2c0-466e-99a3-49b74c69f932.flac][(audio)]]就业的问题很大；要是妇女回家，[[file:2e73f7e1-b3cb-4aca-8f41-057e2e60d2fe.flac][(audio)]]这个问题就比较容易解决了。[[file:e19a1547-f5ee-4c20-b7a9-961eb1376037.flac][(audio)]]

陈老师：为了解决就业问题，[[file:693a60dd-b658-4d3c-8fa7-02088de8753a.flac][(audio)]]就必须让妇女回家吗？[[file:b05ff0a4-e6c3-45c0-b126-3cdd5f1d1168.flac][(audio)]]这不公平。[[file:63bf636e-fde1-4186-a09f-ce39a176e29c.flac][(audio)]]我觉得，[[file:fc9d5e27-55e7-4bf8-ac84-3a412f861123.flac][(audio)]]现在首先要解决[[file:31dfbe95-f22a-4588-9ac6-840bfedab018.flac][(audio)]]就业中的男女平等问题。[[file:62b35270-d2ae-4c11-8dc8-3cd7e3cfe373.flac][(audio)]]比如说，有的工作男女都可以干，[[file:db2270ad-3e9a-46f7-80cc-3147c182f010.flac][(audio)]]可是一些单位只要男的，不要女的。[[file:c7c2e4c3-6ca6-432d-a02d-cfe0ad060a7f.flac][(audio)]]我认为这是很不对的。[[file:42e031c2-8e61-4f0e-949b-4af582d5b801.flac][(audio)]]

陆雨平：你不认为有的工作男人来做更合适吗？[[file:89627733-aff8-40a6-9099-35de0514f60c.flac][(audio)]]

王小云：当然有，[[file:fd57730a-3016-4cd8-afb6-209cc5733569.flac][(audio)]]但是也有的工作妇女比男人做得更好。[[file:04d9b5e7-bda2-4800-a4a1-6a764e7b9a46.flac][(audio)]]重要的是，[[file:9e48693f-7b45-44c6-ab57-e523e869e082.flac][(audio)]]男女都应该有公平竞争的机会。[[file:7a439768-9039-4d31-8075-690b10a5a1aa.flac][(audio)]]

陆雨平：最后，我们不能不谈到这个问题：陈老师，[[file:2b816d62-5ed8-4f8e-bf2a-8ea7ae2d8e38.flac][(audio)]]你认为究竟应该怎样[[file:54a63791-469c-4506-a21c-847944e1ac2d.flac][(audio)]]才能实现男女平等呢？[[file:f1048134-9bcd-4e53-84d3-3b11ef9b2891.flac][(audio)]]

陈老师：只有在各个方面[[file:c1ea3be3-7007-4287-8502-909d5c5d09f4.flac][(audio)]]只有在各个方面[[file:bc84496b-c156-462f-bb53-f140efdeb79e.flac][(audio)]]男女才能平等。[[file:3d08c16d-7068-456c-9ef8-82b7375b7aee.flac][(audio)]]

陆雨平：谢谢你们接受我的访问。[[file:fb2b36c6-69e2-447c-9c5e-04de278ab408.flac][(audio)]]

*** 二



各位老师，各位同学：

我很高兴有机会跟大家谈谈中国妇女的地位问题。这是一个很大的问题，我想从四个方面简单地谈一谈。

首先，我要谈一下中国妇女的社会地位。

中国人常说妇女是“半边天”。“半边天”是什么意思呢？就是妇女几乎担负着一半的社会工作。她们跟男人一样，对社会进步和国家的发展发挥着重要的作用。在全中国的职工中，女职工占百分之四十。现在中国既有女副总理、女部长、女外交官、女经理，又有女科学家、女教授、女画家、女诗人……一般地说，男人能做的工作没有妇女不能做的。有的工作，比如纺织工人、护士，几乎都是妇女；中小学教师，大学里的外语老师，也是女的比男的多。大家都知道，在中国两千多年的封建社会中，妇女没有社会地位。她们一辈子要服从自己的父母、丈夫和儿子。她们没有受教育的权利，也不能走出家门到外边去工作，只能在家里做家务，照顾丈夫和孩子。现在情况不同了，妇女能发挥“半边天”的作用，在社会上有了跟男子平等的地位。这是中国社会的进步。

第二，中国妇女在家庭里的地位。

一般地说，妇女只有社会地位提高了，在家庭里的地位才能提高。她们在外边有自己的工作和经济收入，在家里就有了平等的地位。过去，家里的大事常常由丈夫决定，现在丈夫要跟妻子商量。过去，家务事总是由妻子一个人来做，现在丈夫在家也要发挥“半边天”的作用。很多家庭的家务事都有了分工：常常是丈夫买菜，妻子做饭；丈夫打扫房间，妻子洗衣服；丈夫管孩子学习，妻子管孩子的吃穿。有的外国朋友看到中国男人会做菜，觉得很奇怪。要是你生活在中国人的家里，就会发现丈夫每天也要下厨房，他们的做菜技术就是这样练出来的。当然，总的来说家务事儿妇女要比男人干得多，而且不做家务的丈夫现在也还有。

第三，是职业妇女的困难。

职业妇女在外边担负一定的工作，在家里又担负很重的家务。她们既要做一个好的工作人员，又要做一个好妻子、好母亲，所以生活很不容易，比男人辛苦得多。有的女职工说，一天二十四小时，除了吃饭睡觉以外，几乎没有一分钟是她自己的！她们没有时间学习，没有休闲活动。家庭和事业的矛盾是职业妇女很难解决的问题。

最后我要谈的问题是，现在男女已经平等了吗？

很多中国妇女认为，现在在一些方面还没有完全实现男女平等。比如在就业方面，有的地方对妇女还很不公平，妇女做同样的工作，得到的报酬没有男人高。在一些农村，女孩受教育的机会比男孩少得多；在科学家、教授、经理中，妇女还非常少。这些情况不但中国有，世界很多地方也都有。总的来说，为了完全实现男女平等，我们还有很长的路要走。

谢谢大家。

** 三、练习与运用

*** 2. 句子练习

**** A

***** 几乎
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: 22d4ce67-0fcc-41a6-ba12-f0e002a515b9
:END:

******* 句子填空

昨天去看足球比赛的人多级了，我们班的同学🟦。

******* 词语

去

******* 答案

几乎都去

****** 2
:PROPERTIES:
:ID: a62c1632-208e-4a84-9268-a5bd559a996b
:END:

******* 句子填空


在我们的学校，教外语的老师🟦。
******* 词语

女的

******* 答案

几乎都是女的

****** 3
:PROPERTIES:
:ID: 9ac3e4e5-2049-41dd-8abd-020517b2b513
:END:

******* 句子填空

为了买房子，他🟦把一辈子的积蓄🟦。

******* 词语

花

******* 答案

******** Part 1

几乎

******** Part 2

花完了

****** 4
:PROPERTIES:
:ID: 3629087b-5bd9-4d2d-bacd-eef717f70263
:END:

******* 句子填空

现在的城里人🟦，男的女的都忙工作，实在没有很多时间照顾家庭。

******* 词语

双职工

******* 答案

几乎都是双职工

****** 5
:PROPERTIES:
:ID: 70720001-905a-4e64-93d0-8e3609f21b68
:END:

******* 句子填空

星期六回北京的车票很不好买，我🟦。

******* 词语

回不去

******* 答案

几乎回不去

***** 为了
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: a5b484f0-edb4-4cb9-b09f-ff11a7718814
:END:

******* 句子填空

🟦，妇女就应该回家做家务吗？

******* 词语

就业

******* 答案

为了解决男女就业问题


****** 2
:PROPERTIES:
:ID: 99eafd1c-acf5-4eb1-b094-60c5a35ffa59
:END:

******* 句子填空

🟦，马大为决定来中国留学。

******* 词语



******* 答案



****** 3
:PROPERTIES:
:ID: 124e76dc-1b5d-4f30-81f7-e82dc52c42ce
:END:

******* 句子填空

🟦，他们都 在认真准备。

******* 词语

比赛

******* 答案



****** 4
:PROPERTIES:
:ID: b84d0cb2-4c30-4ec0-b35b-540dfaf3272e
:END:

******* 句子填空

🟦，我们就应该更快地发展都育事业。

******* 词语

经济

******* 答案



****** 5
:PROPERTIES:
:ID: 1a53a1fe-be0e-4b59-8316-b740332fe29d
:END:

******* 句子填空

🟦，我们都要重视环境保护的工作。

******* 词语

人类自己

******* 答案



***** 在……方面
:PROPERTIES:
:NOTETYPE: 3e1fc8b0-2f61-42d1-b781-e615a508b56d
:END:

****** 1
:PROPERTIES:
:ID: 0a93f058-ace9-4881-9b72-9d16447ed2ae
:END:

******* 句子填空

🟦，老师和同学对我帮助很大，所以我的口语进步很快。

******* 词语

no value

******* 答案



****** 2
:PROPERTIES:
:ID: eb9999c7-a970-4459-83e2-788f400b5ec0
:END:

******* 句子填空

🟦，问题不大，我已经向银行贷款了。

******* 词语



******* 答案



****** 3
:PROPERTIES:
:ID: 32c302e6-702f-4124-b0fc-61c4dea2db3e
:END:

******* 句子填空

🟦，主要由她丈夫管，她只管孩子的吃穿。

******* 词语



******* 答案



****** 4
:PROPERTIES:
:ID: 052ee45e-414a-43f3-bdaa-7ecccfe7b21e
:END:

******* 句子填空

🟦，男女还不完全平等，有些工作女的也可以做，可是他们不用女的，只用男的。

******* 词语



******* 答案



****** 5
:PROPERTIES:
:ID: 02a30926-1dc3-4847-aada-755b88a48c46
:END:

******* 句子填空

🟦，妇女比男人的机会少得多。

******* 词语



******* 答案

***** 在……中

****** 词语

******* 1

买习


******* 2

沙漠


******* 3

婚礼


******* 4

事业


******* 5

所有职工

****** 题目

******* 1

******** 句子填空

🟦，几乎看不到植物。

******** 答案

在沙漠中

******* 2

******** 句子填空

🟦，新娘常常要向客人敬酒。

******** 答案

在婚礼中

******* 3

******** 句子填空

🟦，她常重到公司老板的夸奖。

******** 答案

在实习中

******* 4

******** 句子填空

🟦，男的常常比女的多。

******** 答案

在所有职工中

******* 5

******** 句子填空

🟦，他们互相帮助、互相合作。

******** 答案

在事业中
